# Generated by Django 5.2.5 on 2025-08-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_info_options_alter_info_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
