# Generated by Django 5.2.5 on 2025-08-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_info_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
    ]
