# Generated by Django 5.2.5 on 2025-08-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_info_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
