# Generated by Django 5.2.5 on 2025-08-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_info_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
