# Generated by Django 5.2.5 on 2025-08-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_alter_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
