# Generated by Django 5.2.5 on 2025-08-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_experience_to_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
