# Generated by Django 5.2.5 on 2025-08-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
