# Generated by Django 5.2.5 on 2025-08-30 13:44

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_project_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='images'),
        ),
    ]
