# Generated by Django 5.2.5 on 2025-08-30 13:47

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='about_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='info',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='resumes'),
        ),
    ]
